# Generated by Django 5.2.6 on 2026-02-20 21:10

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="archived_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="uses_default_avatar",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="reviews/",
                validators=[main.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("summary", models.CharField(max_length=180)),
                (
                    "preview_image",
                    models.ImageField(
                        upload_to="case-studies/",
                        validators=[main.validators.validate_image_upload],
                    ),
                ),
                ("problem", models.TextField()),
                ("data", models.TextField()),
                ("approach", models.TextField()),
                ("results", models.TextField()),
                (
                    "tech_stack",
                    models.CharField(
                        help_text="Comma-separated values, e.g. Python, Pandas, Django REST.",
                        max_length=220,
                    ),
                ),
                ("github_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=140)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("summary", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[("article", "Article"), ("video", "Video"), ("insight", "Insight")],
                        default="article",
                        max_length=20,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="insights/",
                        validators=[main.validators.validate_image_upload],
                    ),
                ),
                ("video_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
