# Generated by Django 5.2.6 on 2026-02-24 10:35

import django.core.validators
import main.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_review_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="profile-images/",
                        validators=[main.validators.validate_image_upload],
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=140)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=120)),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                ("content", models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)])),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="main.insight",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="main.comment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["insight", "is_active", "created_at"],
                        name="comment_insight_active_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emoji",
                    models.CharField(
                        choices=[
                            ("👍", "Thumbs up"),
                            ("❤️", "Heart"),
                            ("😂", "Laugh"),
                            ("🔥", "Fire"),
                            ("👏", "Clap"),
                            ("💡", "Idea"),
                        ],
                        max_length=8,
                    ),
                ),
                ("user_identifier", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "insight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="main.insight",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["insight", "emoji"], name="reaction_insight_emoji_idx"),
                    models.Index(fields=["user_identifier"], name="reaction_user_id_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("insight", "emoji", "user_identifier"),
                        name="uniq_insight_emoji_user",
                    )
                ],
            },
        ),
    ]
