# Generated by Django 5.2.6 on 2026-02-24 15:20

from django.db import migrations, models


def normalize_reaction_emojis(apps, schema_editor):
    Reaction = apps.get_model("main", "Reaction")
    allowed = {
        "\U0001F44D",
        "\u2764\ufe0f",
        "\U0001F602",
        "\U0001F525",
        "\U0001F44F",
        "\U0001F4A1",
    }

    for reaction in Reaction.objects.all().only("id", "emoji"):
        raw_value = reaction.emoji
        if raw_value in allowed:
            continue
        try:
            normalized = raw_value.encode("latin-1").decode("utf-8")
        except (UnicodeEncodeError, UnicodeDecodeError):
            continue
        if normalized in allowed:
            reaction.emoji = normalized
            reaction.save(update_fields=["emoji"])

    # Keep only the latest reaction per (insight, user_identifier) before applying
    # the stricter unique constraint.
    seen = set()
    for reaction in Reaction.objects.order_by("-created_at", "-id").only(
        "id", "insight_id", "user_identifier"
    ):
        key = (reaction.insight_id, reaction.user_identifier)
        if key in seen:
            reaction.delete()
            continue
        seen.add(key)


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_comment_reaction_profileimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="user_identifier",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.RunPython(normalize_reaction_emojis, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="reaction",
            name="emoji",
            field=models.CharField(
                choices=[
                    ("\U0001F44D", "Thumbs up"),
                    ("\u2764\ufe0f", "Heart"),
                    ("\U0001F602", "Laugh"),
                    ("\U0001F525", "Fire"),
                    ("\U0001F44F", "Clap"),
                    ("\U0001F4A1", "Idea"),
                ],
                max_length=8,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="reaction",
            name="uniq_insight_emoji_user",
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("insight", "user_identifier"),
                name="uniq_insight_user_reaction",
            ),
        ),
    ]
