# Generated by Django 5.2.6 on 2026-03-02 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_comment_identity_and_reaction_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casestudy",
            name="approach",
            field=models.TextField(
                help_text="Maximum 500 characters.",
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="data",
            field=models.TextField(
                help_text="Maximum 500 characters.",
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="problem",
            field=models.TextField(
                help_text="Maximum 500 characters.",
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
        migrations.AlterField(
            model_name="casestudy",
            name="results",
            field=models.TextField(
                help_text="Maximum 500 characters.",
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
    ]
