# Generated by Django 5.2.6 on 2026-03-06 12:58

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_case_study_section_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Concise description of the event.')),
                ('image', models.ImageField(upload_to='events/', validators=[main.validators.validate_image_upload])),
                ('date', models.DateField(blank=True, help_text='Date for chronological sorting.', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual display ordering.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-date', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='reaction',
            name='uniq_insight_user_reaction',
        ),
        migrations.RemoveIndex(
            model_name='reaction',
            name='reaction_insight_emoji_idx',
        ),
        migrations.RemoveIndex(
            model_name='reaction',
            name='reaction_user_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_insight_active_idx',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='Insight',
        ),
    ]
